# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('godonate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='camp_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camp_name', to='godonate.Camp'),
        ),
    ]
