# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godonate', '0003_auto_20171122_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='image',
            field=models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='campimages/'),
        ),
    ]
