# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godonate', '0005_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
