# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godonate', '0006_person_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
